#!/usr/bin/perl
# 2015, Michal Ingeli <mi@v3.sk>, WTF-PL
package Acme::CBHS;

use strict;
use warnings;
use Data::Dumper;

use Math::Random::Secure qw(irand);
use Getopt::Long  qw(:config no_ignore_case bundling);
use File::Slurp;

my %c = (
	words => 6,
	skip_symbols => 1,
	min_length => 4,
	max_length => 8,
	dict => '/usr/share/dict/words',
	count => 1,
	capitalize_first => 0,
	overall_length => 32,
);

my $options = GetOptions(
	'w|words=i' => \$c{words},
	's|symbols' => \$c{skip_symbols},
	'm|min=i' => \$c{min_length},
	'M|max=i' => \$c{max_length},
	'd|dictionary=s' => \$c{dictionary},
	'c|count' => \$c{count},
	'h|help' => \$c{help},
	'C|capitalize-first' => \$c{capitalize_first},
);

my @lines = read_file($c{dict});
my $dice;
my @parts = ();
for (my $i = $c{words}; $i; $i--) {
	my $word;	
	while (1) {
		$word = $lines[irand($#lines)];
		chomp $word;
		$word = lc $word;
		next 
			if (length $word < $c{min_length});
		next
			if (length $word > $c{max_length});
		next
			if ($c{skip_symbols} && $word !~ /^\w+$/);
		$word = ucfirst $word
			if ($c{capitalize_first});
		last;	
	}

	push @parts, $word;
};

printf("%s\n", join(' ', @parts)); 

1;
